#! /bin/bash

git clone https://github.com/lymlan/vim/vimrc ~/vimsetup
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mv ~/vimsetup/vimrc ~/.vimrc
 vim +PluginInstall +qall
rm -rf ~/vimsetup


